name: SWE437HW5 Test for common-kafka

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1
        uses: actions/setup-java@v3
        with:
          java-version: '1'
          distribution: 'adopt'
          architecture: x64
      - run: git clone https://github.com/cerner/common-kafka
  #    - run: git clone https://github.com/TestingResearchIllinois/NonDex
      - run: ls
#      - name: Set up JDK 8
 #       uses: actions/setup-java@v3
  #      with:
   #       java-version: '8'
    #      distribution: 'adopt'
     #     architecture: x64
      #- name: maven NonDex
       # run: mvn install
        #working-directory: NonDex
      - name: Set up JDK 1
        uses: actions/setup-java@v3
        with:
          java-version: '1'
          distribution: 'adopt'
          architecture: x64
      - name: compile the module where the test is, and all modules it depends on
        run: mvn test-compile -pl common-kafka -am -e
        working-directory: common-kafka
      - name: run the test to check that it passes
        run: mvn -pl common-kafka test -Dtest=com.cerner.common.kafka.consumer.ProcessingKafkaConsumerTest#nextRecord_fairProcessing
        working-directory: common-kafka
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
      - name: if the test passes in regular runs, see if it fails with the NonDex tool that reports flaky tests
        run: mvn -pl common-kafka edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.cerner.common.kafka.consumer.ProcessingKafkaConsumerTest#nextRecord_fairProcessing -DnondexRuns=20 
        working-directory: common-kafka
