name: SWE437HW5 Test for nifi

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
      - run: git clone https://github.com/apache/nifi
      - run: git clone https://github.com/TestingResearchIllinois/NonDex
      - run: ls
      #- name: check all versions
      #  run: git log
     #   working-directory: nifi
      - name: maven NonDex
        run: mvn install
        working-directory: NonDex
      - name: check out ba7271c85b59cb62a66282360f90eba3e3f0b5ba
        run: git checkout ba7271c85b59cb62a66282360f90eba3e3f0b5ba
        working-directory: nifi
      - name: maven clean install
        run: mvn clean install -DskipTests -pl nifi-registry/nifi-registry-core/nifi-registry-framework -am
        working-directory: nifi
      - name: compile the module where the test is, and all modules it depends on
        run: mvn test-compile -pl nifi-registry/nifi-registry-core/nifi-registry-framework -am -e
        working-directory: nifi
      - name: run the test to check that it passes
        run: mvn -pl nifi-registry/nifi-registry-core/nifi-registry-framework test -Dtest=org.apache.nifi.registry.security.ldap.tenants.LdapUserGroupProviderTest#testSearchGroupsWithNoNameAttribute
        working-directory: nifi
      - name: if the test passes in regular runs, see if it fails with the NonDex tool that reports flaky tests
        run: mvn -pl nifi-registry/nifi-registry-core/nifi-registry-framework test edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.nifi.registry.security.ldap.tenants.LdapUserGroupProviderTest#testSearchGroupsWithNoNameAttribute
        working-directory: nifi

